version: '3.5'
services:
  server1:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ".:/go/src/github.com/hakobe/grpc-try-load-balancing"
    environment:
      HOST_PORT: 0.0.0.0:5000
    command: go run server/main.go
  server2:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ".:/go/src/github.com/hakobe/grpc-try-load-balancing"
    environment:
      HOST_PORT: 0.0.0.0:5000
    command: go run server/main.go
  server3:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ".:/go/src/github.com/hakobe/grpc-try-load-balancing"
    environment:
      HOST_PORT: 0.0.0.0:5000
    command: go run server/main.go
  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - server1
      - server2
      - server3
    volumes:
      - ".:/go/src/github.com/hakobe/grpc-try-load-balancing"
    environment:
      HOST_PORT: 0.0.0.0:5000
    command: go run client/main.go
